let suggestions = [
    "Naruto Volume 72",
    "A Game of Thrones",
    "Full Metal Alchemist Volume 27",
    "Noragami Volume 1",
    "Computer Networking, 8th Edition",
    "The Lord of The Rings",
    "Bleach Volume 57",
    "Demon Slayer Volume 8",
    "Death Note Volume 10",
    "Introduction to the Design and Analysis of Algorithms, 3rd Edition",
    "Data Structures & Algorithm Analysis in C++",
    "Mastering Regular Expressions",
    "Mathematics for Machine Learning",
    "Succeeding with Agile: Software Development Using Scrum",
    "Artificial Intelligence: A Modern Approach",
    ">One Piece Volume 59",
    "Operating System Concepts",
    "Database System Concepts",
    "Deep Learning with Python",
    "Web Programming and Internet Technologies",
    "Verity",
    "Shadow Me",
    "The Witcher - Sword of Destiny",
    "Animal Farm",
    "Inferno",
    
];

